### ISSUE TITLE
게임 룸 관리 방안 설계

### ISSUE THREAD

**Issue by intovery** [B0ttle-Cat/Project-TF#11]
* 인증 완료 된 유저가 GAMEROOM_ENTER 요청 시, 게임 룸 생성 및 입장 처리
* 룸에 유저가 아무도 없을 시, 일정 시간 지난 후 룸 제거 처리

**Comment by B0ttle-Cat** [comment]
입장 응답값으로 유저마다 시작하는 룸 위치 넣어주시면 감사하겠습니다.

**Comment by intovery** [comment]
Overview 문서화 완료

https://escapeportfolioteam.atlassian.net/wiki/spaces/1/pages/6455940

**Comment by intovery** [comment]
Client <-> Room-Manage Server API 문서화 완료

https://escapeportfolioteam.atlassian.net/wiki/spaces/1/pages/6619150

**Comment by intovery** [comment]
Client <-> Logic Server패킷 + 시퀀스 문서화 완료

https://escapeportfolioteam.atlassian.net/wiki/spaces/1/pages/4259841

**Comment by intovery** [comment]
게임 룸 관리 시퀀스 일부 수정

게임 룸에 대기방 개념 적용(대기방에 유저들이 모이고, 게임 시작은 이후 별도 시퀀스를 통해 진행)

게임 룸 입장: https://escapeportfolioteam.atlassian.net/wiki/spaces/1/pages/4259841
게임 시작: https://escapeportfolioteam.atlassian.net/wiki/spaces/1/pages/6782978
